dev:
  restart: always
  container_name: ethdevcon
  build: ./
  stdin_open: true
  tty: true
  ports:
    - "22:22"
    - "8080:8080"
    - "8545:8545"
  environment:
    - DATABASE_HOST=db
  volumes:
    - ~/:/var/mac
